version: '3'
services:

  db:
    image: postgres:12.2
    volumes:
      - ./db_data_ps:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=alizarine
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'